name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.2.0
  provider: ^6.0.2
  uuid: ^4.0.0
  go_router: ">=10.0.0 <14.0.0"
  collection: ^1.16.0
  http: ^0.13.3 # 添加 http 包
  geolocator: ^7.6.0 # 确认当前版本号
  hive: ^2.2.3
  hive_flutter: ^1.1.0
#  location: ^4.3.0


dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

  uses-material-design: true

